### ISSUE TITLE
How to fix url contain Chinese words?

### ISSUE THREAD

**Issue by sha0123** [Golim/wcde#1]
it keeps showing "'latin-1' codec can't encode characters in position 30-31: ordinal not in range(256)" while testing, how can i fix it?

**Comment by Golim** [comment]
Could you provide more information? What site are you testing? A specific URL that causes this error?

**Comment by sha0123** [comment]
Thanks for your reply. Site like "www.hkood.com" would cause this error.

**Comment by Golim** [comment]
Should be fixed now, let me know if you still have this issue

**Comment by sha0123** [comment]
It is fixed now. Thanks for your help.
